apiVersion: v1
kind: Pod
metadata:
  name: foodybuddy-web
  labels:
    app: foodybuddy-web
    component: web
spec:
  containers:
  - name: foodybuddy-web
    image: foody-buddy-app-foodybuddy-web:v2
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3000
      protocol: TCP
    env:
    - name: NODE_ENV
      value: "production"
    - name: PORT
      value: "3000"
    - name: HOSTNAME
      value: "0.0.0.0"
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    # livenessProbe:
    #   httpGet:
    #     path: /
    #     port: 3000
    #   initialDelaySeconds: 30
    #   periodSeconds: 10
    # readinessProbe:
    #   httpGet:
    #     path: /
    #     port: 3000
    #   initialDelaySeconds: 5
    #   periodSeconds: 5
